# Generated by Django 6.0.5 on 2026-05-22 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('city', 'Shahar'), ('region', 'Viloyat')], default='city', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('uzs', "So'm"), ('usd', 'USD'), ('eur', 'Euro')], db_index=True, default='uzs', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('used', 'B/U')], default='new', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('has_delivery', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('sold', 'Sotilgan'), ('archived', 'Arxivlangan'), ('deleted', "O'chirilgan")], db_index=True, default='active', max_length=25)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.district')),
                ('listing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_listings', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.region')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='ListingContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=120)),
                ('allow_chat', models.BooleanField(default=True)),
                ('allow_call', models.BooleanField(default=False)),
                ('allow_telegram', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='listings.listing')),
            ],
            options={
                'verbose_name': "E'lon aloqa ma'lumoti",
                'verbose_name_plural': "E'lon aloqa ma'lumotlari",
                'db_table': 'listing_contacts',
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "E'lon ko'rilishi",
                'verbose_name_plural': "E'lon ko'rilishlari",
                'db_table': 'listing_views',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='listings/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Rasm asosiymi')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion_type', models.CharField(choices=[('top', 'Top'), ('urgent', 'Shoshilinch'), ('pro', 'Pro'), ('highlight', 'Ajratilgan')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='listings.listing')),
            ],
            options={
                'verbose_name': "E'lon promo",
                'verbose_name_plural': "E'lon promolari",
                'db_table': 'listing_promotions',
            },
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewed', "Ko'rilgan"), ('rejected', 'Rad etilgan'), ('resolved', 'Hal qilingan')], default='new', max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "E'lon shikoyati",
                'verbose_name_plural': "E'lon shikoyatlari",
                'db_table': 'listing_reports',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='listings.region'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_category', 'status'], name='listing_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_category', 'price'], name='listing_category_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_category', 'currency'], name='listing_category_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['region', 'district', 'status'], name='region_district_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at', 'status'], name='created_at_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', 'created_at'], name='lview_listing_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['user', 'created_at'], name='lview_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['session_key', 'created_at'], name='lview_session_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='unique_region_district_slug'),
        ),
    ]
