# Generated by Django 6.0.5 on 2026-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingview',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
