# Generated by Django 6.0.5 on 2026-05-22 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_favorites', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saqlangan',
                'verbose_name_plural': 'Saqlanganlar',
                'db_table': 'favorites',
                'constraints': [models.UniqueConstraint(fields=('user', 'favorite_listing'), name='unique_user_favorite_listing')],
            },
        ),
    ]
