# Generated by ChatGPT on 2026-05-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerApplication",
            fields=[
                ("id", models.UUIDField(default=__import__("uuid").uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("business_name", models.CharField(max_length=180)),
                ("contact_phone", models.CharField(max_length=20)),
                ("business_description", models.TextField(blank=True)),
                ("telegram_username", models.CharField(blank=True, max_length=100)),
                ("is_store", models.BooleanField(default=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_seller_applications", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="seller_application", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Sotuvchi arizasi",
                "verbose_name_plural": "Sotuvchi arizalari",
                "db_table": "seller_applications",
            },
        ),
    ]
